### ISSUE TITLE
Error when trying to view or modify package with no `version` property

### ISSUE THREAD

**Issue by mmalecki** [npm/newww#1342]
Reproducable by, for example, `curl https://www.npmjs.com/package/formula/access`:

```
Unhandled rejection TypeError: Cannot call method 'replace' of undefined
  at [object Object].Collaborator.list (/mnt/deploys/newww/models/collaborator.js:25:63)
  at Package.get.catch.then.then.cpackage.collaborators (/mnt/deploys/newww/handlers/access.js:34:27)
  at tryCatcher (/mnt/deploys/newww/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._settlePromiseFromHandler (/mnt/deploys/newww/node_modules/bluebird/js/main/promise.js:454:31)
  at Promise._settlePromiseAt (/mnt/deploys/newww/node_modules/bluebird/js/main/promise.js:530:18)
  at Promise._settlePromises (/mnt/deploys/newww/node_modules/bluebird/js/main/promise.js:646:14)
  at Promise.b (domain.js:183:18)
  at Async._drainQueue (/mnt/deploys/newww/node_modules/bluebird/js/main/async.js:182:12)
  at Async._drainQueues (/mnt/deploys/newww/node_modules/bluebird/js/main/async.js:187:10)
  at Async.drainQueues (/mnt/deploys/newww/node_modules/bluebird/js/main/async.js:15:14)
  at process._tickDomainCallback (node.js:492:13)
```

**Comment by mmalecki** [comment]
As it turns out, unauthenticated vs authenticated does not matter - that particular package has no `version` property, thus making presenter throw an "invalid pkg" error here: https://github.com/npm/newww/blob/master/presenters/package.js#L25

This appears to be an issue we've seen before but never debugged (I *think* npm/issue-tracker#49 might be it). I'll rename accordingly and close if I find an exact duplicate.

**Comment by mmalecki** [comment]
After initial investigation it would appear that we should be able to remove that check altogether - package pages and access pages still display fine without it, even those without a `version` property.
