### ISSUE TITLE
npm yo installation issue

### ISSUE THREAD

**Issue by arushijain45** [npm/newww#1588]
Hello people. I have installed npm 3.5.0, and yaemon in my system ubuntu 12.0.4 using following command:
sudo npm install -g yo
But when I try to check it using following command yo --version, it shows me this error. I have struggled it everywhere but could not get working solution.

module.js:339
throw err;
^

Error: Cannot find module 'duplexify'
at Function.Module._resolveFilename (module.js:337:15)
at Function.Module._load (module.js:287:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at Object. (/usr/lib/node_modules/yo/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/index.js:10:17)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Module.require (module.js:366:17)

Please help.

**Comment by aredridel** [comment]
Alright! You'll probably want to file an issue in the http://github.com/npm/npm repository -- this one is for the website, not the command line tool -- or send an email to support@npmjs.com

However, you can likely fix that error by running `sudo npm install -g yo` again. Especially if it was previously installed with npm 2, that can happen.
