### ISSUE TITLE
issue running tests locally

### ISSUE THREAD

**Issue by coleGillespie** [npm/newww#525]
i am trying to create some more tests for some code i just added but am having trouble running tests locally. I am wondering if you have seen anything similar to this

```
coles-iMac:newww cole$ npm test

> newww@2.0.0 test /Users/cole/Public/github/newww
> lab --verbose --colors --ignore '$$bole'


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by coleGillespie** [comment]
actually my fault, was not running tests from vagrant
