### ISSUE TITLE
Running npm run dev outside of vm fails

### ISSUE THREAD

**Issue by gtanner** [npm/newww#612]
In the readme it states the ideal way to run the dev script is outside of the vm.

but it looks like there is a native dep in a module that now prevents this:

```
odule.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build/Release/onig_scanner.node, 1): no suitable image found.  Did find:
	/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build/Release/onig_scanner.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/lib/oniguruma.js:4:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/lib/oniguruma.js:65:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/lib/grammar.js:10:16)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/lib/grammar.js:336:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/lib/grammar-registry.js:14:13)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/lib/grammar-registry.js:230:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/lib/first-mate.js:4:22)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/node_modules/first-mate/lib/first-mate.js:8:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/lib/highlights.js:10:21)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/node_modules/highlights/lib/highlights.js:150:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/lib/render.js:2:24)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/node_modules/marky-markdown/index.js:4:19)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/services/corporate/methods/getPage.js:3:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.exports.register (/Users/gtanner/Projects/newww/services/corporate/index.js:6:33)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Object.Registry (/Users/gtanner/Projects/newww/services/registry/index.js:78:10)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Object.User [as register] (/Users/gtanner/Projects/newww/services/user/index.js:29:3)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Object.exports.register (/Users/gtanner/Projects/newww/node_modules/blankie/lib/index.js:285:12)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Object.exports.register (/Users/gtanner/Projects/newww/node_modules/scooter/lib/index.js:15:12)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Object.exports.register (/Users/gtanner/Projects/newww/node_modules/crumb/lib/index.js:164:12)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at Object.exports.serial (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:38:9)
  at [object Object].internals.Plugin.register (/Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:221:11)
  at /Users/gtanner/Projects/newww/server.js:71:10
  at done (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:30:25)
  at Object.exports.register (/Users/gtanner/Projects/newww/node_modules/hapi-auth-cookie/lib/index.js:15:5)
  at /Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:235:14
  at iterate (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at Object.exports.serial (/Users/gtanner/Projects/newww/node_modules/hapi/node_modules/items/lib/index.js:38:9)
  at [object Object].internals.Plugin.register (/Users/gtanner/Projects/newww/node_modules/hapi/lib/plugin.js:221:11)
  at Object.<anonymous> (/Users/gtanner/Projects/newww/server.js:39:8)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by zeke** [comment]
It looks like you're having trouble installing `oniguruma`, the regex parser used by the `highlights` syntax highlighter. First of all, please pull the latest code and give `npm install` another try. If that doesn't work, please let use know what version of `node` or `iojs` you're running, and the version of `npm` too. Thanks.
