### ISSUE TITLE
config must specify a mailTransportModule

### ISSUE THREAD

**Issue by zeke** [npm/newww#688]
I see the setting in `config.js`, yet this error is thrown. An idea what's up, @rockbot?

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: config must specify a `mailTransportModule`
    at Object.<anonymous> (/Users/z/n/www/server.js:23:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by zeke** [comment]
Gah, I had it overridden in `config.admin.js`. Now deleting `config.admin.js`
